CREATE TABLE seljan.Students(
       Student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       first_name varchar2(50) Not Null,
       last_name varchar2(50) Not Null,
       birth_date date,
       gender varchar2(10),
       email varchar2(100) unique,
       phone Varchar2(20),
       created_at timestamp default current_timestamp
);
Create table seljan.Instructors(
       Instructor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       first_name varchar2(50),
       last_name varchar2(50),
       specialization varchar2(100),
       email varchar2(100) unique,
       phone Varchar2(20),
       hire_date date,       
       created_at timestamp default current_timestamp
);
Create table seljan.Classes(
       Class_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       class_name varchar2(100),
       class_code varchar2(20) unique,
       credit Number(2),
       instructor_id Number,
       semester Varchar2(20),   
       created_at timestamp default current_timestamp,
       Constraint fr_Instructor Foreign Key (Instructor_ID) References seljan.Instructors(Instructor_ID)
);
Create table seljan.Enrollments(
       Enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       student_id Number,
       class_id Number,
       Enrollment_date date,
       Status Varchar2(20) Check (Status IN('Aktiv', 'Tamamlanib', 'Legv edilib')),
       CONSTRAINT unq_student_class Unique(student_id,class_id),
       Constraint fr_student Foreign Key (student_id) References seljan.students(student_id),
       Constraint fr_class Foreign Key (class_id) References seljan.Classes(class_id)
);
Create table seljan.Grades(
       Grade_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       student_id Number,
       class_id Number,
       grade_value Number Check(grade_value between 0 and 100),--between 0 and 100
       grade_type Varchar2(20) Check(grade_type in ('quiz', 'midterm', 'final')),
       Constraint fr_student_grade Foreign Key (student_id)References seljan.students(student_id),
       Constraint fr_class_grade Foreign Key (class_id)References seljan.Classes(class_id)
);
INSERT INTO seljan.Instructors (first_name, last_name, specialization, email, phone, hire_date)
VALUES ('Karim', 'Karimov', 'IT', 'karim.v.karimov@gmail.com', '+994703696448', TO_DATE('09.09.2015', 'DD.MM.YYYY'));
INSERT INTO seljan.Instructors (first_name, last_name, specialization, email, phone, hire_date)
VALUES ('Leyla', 'Aliyeva', 'Mathematics', 'leyla.m@gmail.com', '+994551234567', TO_DATE('15.01.2018', 'DD.MM.YYYY'));
INSERT INTO seljan.Instructors (first_name, last_name, specialization, email, phone, hire_date)
VALUES ('Anar', 'Hasanov', 'Physics', 'anar.h@gmail.com', '+994509876543', TO_DATE('20.08.2016', 'DD.MM.YYYY'));
INSERT INTO seljan.Instructors (first_name, last_name, specialization, email, phone, hire_date)
VALUES ('Nargiz', 'Mammadova', 'Data Science', 'nargiz.m@gmail.com', '+994701112233', TO_DATE('10.11.2019', 'DD.MM.YYYY'));
INSERT INTO seljan.Instructors (first_name, last_name, specialization, email, phone, hire_date)
VALUES ('Rashad', 'Guliyev', 'Networking', 'rashad.g@gmail.com', '+994514445566', TO_DATE('05.05.2017', 'DD.MM.YYYY'));

INSERT INTO seljan.Students (first_name, last_name, birth_date, gender, email, phone)
VALUES ('Seljan', 'Karimli', TO_DATE('31.08.2005', 'DD.MM.YYYY'), 'Female', 'selkakva@gmail.com', '+994503696448');
INSERT INTO seljan.Students (first_name, last_name, birth_date, gender, email, phone)
VALUES ('Shams', 'Karimova', TO_DATE('10.07.2000', 'DD.MM.YYYY'), 'Female', 'shamskarimova2000s@gmail.com', '+994503366050');
INSERT INTO seljan.Students (first_name, last_name, birth_date, gender, email, phone)
VALUES ('Ali', 'Valiyev', TO_DATE('12.03.2001', 'DD.MM.YYYY'), 'Male', 'ali.v@mail.com', '+994552223344');
INSERT INTO seljan.Students (first_name, last_name, birth_date, gender, email, phone)
VALUES ('Aysel', 'Sadigova', TO_DATE('25.12.2002', 'DD.MM.YYYY'), 'Female', 'aysel.s@mail.com', '+994507778899');
INSERT INTO seljan.Students (first_name, last_name, birth_date, gender, email, phone)
VALUES ('Tural', 'Nabiyev', TO_DATE('05.06.1999', 'DD.MM.YYYY'), 'Male', 'tural.n@mail.com', '+994705554433');
INSERT INTO seljan.Students (first_name, last_name, birth_date, gender, email, phone)
VALUES ('Gunel', 'Ismayilova', TO_DATE('18.09.2003', 'DD.MM.YYYY'), 'Female', 'gunel.i@mail.com', '+994519990011');
INSERT INTO seljan.Students (first_name, last_name, birth_date, gender, email, phone)
VALUES ('Murad', 'Ahmadov', TO_DATE('22.01.2001', 'DD.MM.YYYY'), 'Male', 'murad.a@mail.com', '+994506665544');
INSERT INTO seljan.Students (first_name, last_name, birth_date, gender, email, phone)
VALUES ('Fidan', 'Gasimova', TO_DATE('30.04.2002', 'DD.MM.YYYY'), 'Female', 'fidan.g@mail.com', '+994708887766');
INSERT INTO seljan.Students (first_name, last_name, birth_date, gender, email, phone)
VALUES ('Emil', 'Bagirov', TO_DATE('14.11.2000', 'DD.MM.YYYY'), 'Male', 'emil.b@mail.com', '+994554443322');
INSERT INTO seljan.Students (first_name, last_name, birth_date, gender, email, phone)
VALUES ('Zahra', 'Rzayeva', TO_DATE('02.02.2004', 'DD.MM.YYYY'), 'Female', 'zahra.r@mail.com', '+994501110099');

INSERT INTO seljan.Classes (class_name, class_code, credit, instructor_id, semester)
VALUES ('Database Systems', 'CS301', 6, 1, 'Fall 2024');
INSERT INTO seljan.Classes (class_name, class_code, credit, instructor_id, semester)
VALUES ('Calculus I', 'MATH101', 5, 2, 'Fall 2024');
INSERT INTO seljan.Classes (class_name, class_code, credit, instructor_id, semester)
VALUES ('Quantum Physics', 'PHYS202', 6, 3, 'Spring 2024');
INSERT INTO seljan.Classes (class_name, class_code, credit, instructor_id, semester)
VALUES ('Machine Learning', 'AI401', 8, 4, 'Fall 2024');
INSERT INTO seljan.Classes (class_name, class_code, credit, instructor_id, semester)
VALUES ('Network Security', 'NET505', 4, 5, 'Spring 2024');

INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (1, 1, CURRENT_DATE, 'Aktiv');
INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (2, 1, CURRENT_DATE, 'Aktiv');
INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (3, 2, CURRENT_DATE, 'Aktiv');
INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (4, 2, CURRENT_DATE, 'Tamamlanib');
INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (5, 3, CURRENT_DATE, 'Aktiv');
INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (6, 3, CURRENT_DATE, 'Legv edilib');
INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (7, 4, CURRENT_DATE, 'Aktiv');
INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (8, 4, CURRENT_DATE, 'Aktiv');
INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (9, 5, CURRENT_DATE, 'Tamamlanib');
INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (10, 5, CURRENT_DATE, 'Aktiv');
INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (1, 2, CURRENT_DATE, 'Aktiv');
INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (2, 4, CURRENT_DATE, 'Aktiv');
INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (3, 5, CURRENT_DATE, 'Aktiv');
INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (5, 1, CURRENT_DATE, 'Tamamlanib');
INSERT INTO seljan.Enrollments (student_id, class_id, Enrollment_date, Status) VALUES (10, 4, CURRENT_DATE, 'Aktiv');

INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (1, 1, 85, 'midterm');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (1, 1, 90, 'final');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (2, 1, 75, 'midterm');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (2, 1, 80, 'final');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (3, 2, 92, 'midterm');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (4, 2, 88, 'final');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (5, 3, 70, 'midterm');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (7, 4, 95, 'midterm');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (7, 4, 98, 'final');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (8, 4, 60, 'quiz');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (9, 5, 82, 'final');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (10, 5, 77, 'midterm');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (1, 2, 85, 'quiz');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (2, 4, 88, 'midterm');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (3, 5, 90, 'final');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (5, 1, 100, 'final');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (10, 4, 85, 'quiz');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (1, 1, 15, 'quiz');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (4, 2, 90, 'quiz');
INSERT INTO seljan.Grades (student_id, class_id, grade_value, grade_type) VALUES (9, 5, 10, 'quiz');
--butun telebelerin siyahisi
select * from seljan.students;
--mueyyen muellimin kecdiyi dersler
select class_name from seljan.classes
where instructor_id=1;
--mueyyen telebenin yazildigi dersler
select class_name from seljan.classes
where class_id IN (select class_id from seljan.enrollments where student_id=1);--2den cox qiymet qaytardigi ucun evvelki = sehv verdi gererk IN yazasan
--mueyyen telebening butun qiymetleri
select grade_value from seljan.grades
where student_id=1;
--her ders uzre telebe sayi
select class_id, count(*) from seljan.enrollments group by class_id;
--her telebenin orta qiymeti
select avg(grade_value) from seljan.grades group by student_id;
--qiymeti 51den asagi olan telebeler
select student_id, grade_value from seljan.grades where grade_value<51;
--muellim+ders siyahisi join ile
select i.first_name||' '||i.last_name as name, 
       i.specialization, 
       i.email, 
       i.phone,
       i.hire_date,
       c.class_name,
       c.class_code,
       c.credit as cr,
       c.semester
  from seljan.instructors i,
       seljan.classes c
 where i.instructor_id=c.instructor_id;
--telebe+ders+qiymet birge hesabati
select s.first_name||' '||s.last_name as name,
       s.birth_date,
       s.gender,
       s.email,
       s.phone,
       c.class_name,
       c.class_code,
       c.credit as cr,
       c.semester,
       g.grade_value,
       g.grade_type
  from seljan.students s,
       seljan.classes c,
       seljan.grades g
 where g.student_id=s.student_id and g.class_id=c.class_id;
--en yuksek orta qiymete sahib telebeler
select * from (select student_id,avg(grade_value) as ortalama from seljan.grades group by student_id order by ortalama desc) where rownum < 4;
commit;
